name: Package templates for rebuild test
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/temp-package-templates-for-rebuild.yml'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            templates
          sparse-checkout-cone-mode: true
      - uses: actions/upload-artifact@v4
        with:
          name: live-templates
          path: templates/
          compression-level: 6
